### ISSUE TITLE
graphs are empty

### ISSUE THREAD

**Issue by jhautefeuille** [dperson/smokeping#10]
I've just download last image.
Smokeping run but graphes are not done.

I'm running Docker on synology.

If I want to trace I must run as crontab on synology

docker exec smokeping --debug 

Container must be autonomous ?

**Comment by dperson** [comment]
Container must be autonomous ?

Is that an error message that you're getting? I'm not sure that I follow or
understand...

-- 
David P.

**Comment by jhautefeuille** [comment]
Smokeping runs, data are collected.

But graphs are empty. 

Normaly with Smokeping, to graph we must use in crontab :

10   *    *   *   *   /usr/local/bin/smokeping --static=/var/www/htdocs/smokeping/ >> /dev/null 2>&1

So question are :

has container a crontab line to trace graphs ? Or maybe we use docker exec smoking... to trace graph ?

**Comment by dperson** [comment]
Even if there was a crontab, I'm not starting the cron daemon. It's working
and graphing for me, and has all along. In the other bug report, there's a
group of users who aren't getting graphs if they don't run the smokeping
daemon as root. Have you tried running it, when setting the `SPUSER`, IE
something like:

    docker run --name smokeping -p 8000:80 -e SPUSER=root -d
dperson/smokeping

Hopefully that will resolve the problem for you too.

-- 
David P.

**Comment by jhautefeuille** [comment]
-e SPUSER=root solves the problem !  

It could be nice to write it in the README.

Thank you very much for feedback !

**Comment by dperson** [comment]
I have now added the option to the README.md (this morning), I'll also note
it in the troubleshooting section, now that I have confirmation that it
fixes the issue. Thanks.

-- 
David P.

**Comment by jhautefeuille** [comment]
I confirm to you that this solution solve my problem.

Again thank you.
