### ISSUE TITLE
Support for EchoPingHttp and EchoPingHttps

### ISSUE THREAD

**Issue by oppianmatt** [dperson/smokeping#11]
I know we could create our own config but it would be a nice feature to add support for adding http and https pings via the smokeping.sh

Maybe even someting like:

```
sudo docker exec <name_of_instance> smokeping.sh -t "<site;name;http://target>"
```

So like the ping but if it sees http or https it makes a EchoPingHttp or EchoPingHttps target.

**Comment by dperson** [comment]
Okay, I'd consider it to be at *EXPERIMENTAL* status right now... I just
added the ability to set http(s) targets. I haven't been able to test it
yet, and probably won't be able to till this evening at least. If you test
it before I do, let me know if it works.

-- 
David P.

**Comment by oppianmatt** [comment]
I get an error:

```
# docker exec smokeping smokeping.sh -t "google;https;https://www.google.com"
sed: -e expression #1, char 17: unknown command: `/'
```

It does add this to `Targets` still:

```
++ https
menu = https
title = https
host = https://www.google.com
```

But seems it's missing the `probe = EchoPingHttps`

**Comment by oppianmatt** [comment]
I've tested out using this for the sed command, seems to work:

```
sed "\|^host = $target| a\
probe = EchoPingHttps
"
```

But the eol $ still had issues. So in the end I went with this:

```
grep -v "probe = EchoPingHttps" < testfile | sed "/^host = https/ a\
probe = EchoPingHttps
"
```

Remove all probes with https, and then add the https probe after all https hosts.

**Comment by oppianmatt** [comment]
One more issue:

ERROR: /etc/smokeping/config.d/Targets, line 25: probe EchoPingHttps missing from the Probes section

**Comment by dperson** [comment]
Hey sorry it took so long, life just got in the way.

I played with it this morning, and think that it's working now, if you want to give it another try.
