### ISSUE TITLE
Support for adjusting step / packetsize etc...?

### ISSUE THREAD

**Issue by sammcj** [dperson/smokeping#12]
It would be great if you could pass in more options such as `step`, `packetsize` etc....

http://oss.oetiker.ch/smokeping/probe/FPing.en.html

**Comment by dperson** [comment]
Sorry but that sounds like quite an edge case as far as usage goes... I'm
just trying to make the most common monitoring really easy. For advanced
configuration, you'll need to update the config and share it in as a
volume. **NOTE** the `<>` are not literal, but indicate the place you
should put the real value

    docker cp <name_of_running_smokeping_container>:/etc/smokeping
</local/path>

That will copy the base config files out of the docker container to the
path you specify. Once you have them you can make any changes that you want
to them. You can then specify that directory be used in a new smokeping
container.

    docker rm <name_of_running_smokeping_container>
    docker run --name smokeping -p 8000:8000 -v
</local/path>:/etc/smokeping:ro -d dperson/smokeping

-- 
David P.
