### ISSUE TITLE
Error when starting smokeping with latest code

### ISSUE THREAD

**Issue by joelnb** [dperson/smokeping#14]
In commit 5d05351fb868699eb3695603a78fa0a37cb42cfd you said 'Dockerfile / smokeping.sh revert some unneeded changes from pull, no errors were in the build logs' just to be clear the error this change was intended to fix was not a build error - it was an error when you actually start and run the system with an EchoPingHttp target.

Example:
```
docker run -P -e SPUSER=root -d dperson/smokeping -t "GOOG;google.com;http://google.com" -o "Joel"
```

With the revert you made this gives me the following error when accessing the smokeping site:
`ERROR: /etc/smokeping/config.d/Targets, line 31: probe must be defined before the host or any probe variables`

I don't get this error with those changes included. Possibly I should have been more clear and incuded this as a separate pull request with an explanation (as it is definitely not a bashism) so sorry about that, I'm quite new to the PR process as I mainly just use Git for work.

**Comment by dperson** [comment]
Ah, I gotcha now, sorry about that. The fix is included now. Thanks.

-- 
David P.
