### ISSUE TITLE
how to set targets via new Targets file

### ISSUE THREAD

**Issue by nandv** [dperson/smokeping#17]
(new to docker so bear with me with this question)
How can I modify the etc/smokeping/config.d/Targets to my specific network environments? 
Thanks.

**Comment by dperson** [comment]
I believe that I covered that in the README.md file... I tried to cover the common use cases, see if it covers what you need. You can view it at the docker hub, or on github:

https://hub.docker.com/r/dperson/smokeping/
https://github.com/dperson/smokeping/

Please let me know if the documentation doesn't cover your needs, and I'll see what I can do.

Thanks.
