### ISSUE TITLE
Can you tell me how to configure the master / slave？ thank you。

### ISSUE THREAD

**Issue by lylang** [dperson/smokeping#21]

**Comment by dperson** [comment]
That's not something that I really looked at implementing in the container. The LoE (Level of Effort) to add shared secrets, and to specify the slaves per test is higher than my interest in it.

If you'd like, I can add a way to start the container as a slave and pass in the master URL (it's shared secret could be an `environment variable`). The master would still have to be configured manually (it's configuration can be stored in an `-v` external volume).

**Comment by lylang** [comment]
think you,If you can give a better method

**Comment by lylang** [comment]
thank you,If you can give a better  method？@dperson

**Comment by dperson** [comment]
I'm not sure that I understand your question...

**Comment by lylang** [comment]
Can you help me write a master / slave approach? or tell me how doing

**Comment by dperson** [comment]
I've never needed to use a master / slave configuration of smokeping... so I'll have to point you to web sites that have information about it.

 * The [official site](http://oss.oetiker.ch/smokeping/doc/smokeping_master_slave.en.html)
 * Another site with a [tutorial](http://will.ninja/smokeping-master-slave-tutorial/)
