### ISSUE TITLE
can not start container: lighthttpd log.c can not write to /dev/stderr

### ISSUE THREAD

**Issue by ties** [dperson/smokeping#22]
Hi,

This is a quick bug report. Unfortunately I do not have time to create and test
a pull request right now.

## Situation:
Today I pulled the newest revision of the container. Afterwards, a new container
 instance would not start.
 
I appear to hit an [issue](https://github.com/docker/docker/issues/6880) where /dev/stderr is not writable for some process.
lighthttpd is writing to this file after dropping privileges and it fails.

The changes in `smokeping.sh` chown this file but do not appear to work.

My environment:
```
$ docker --version
Docker version 1.11.2, build b9f10c9
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux testing (stretch)
Release:        testing
Codename:       stretch
$ uname -a
Linux HOST 4.6.0-1-amd64 #1 SMP Debian 4.6.2-2 (2016-06-25) x86_64 GNU/Linux
$ docker inspect dperson/smokeping
[
    {
        "Id": "sha256:51a32e573b7e37899ec8ba17ff866738fd9e4fa1486735379a5902cadfde0494",
…
```
## Workaround;
I fixed this by starting an alternative script as the entrypoint for the
container (included below). That script is a kludge.

It does:
  * log to a named pipe ([docker issue](https://github.com/docker/docker/issues/6880))
  * remove the `server.errorlog` from lighthttpd.conf ([lighthttpd issue](https://redmine.lighttpd.net/issues/2731))
    * lighthttpd output goes into this named pipe
  * launch smokeping setup to log to this pipe.

I am not sure if all those steps were needed. If you prefer it, I could provide
 a tested pull request when I have spare time.

The script (kludge):
```
#!/usr/bin/env bash
# from <https://redmine.lighttpd.net/issues/2731>
# first: remove the server.errorlog line
sed -i 's/^server.errorlog.*$//g' /etc/lighttpd/lighttpd.conf

# from <https://github.com/docker/docker/issues/6880>
# Create a named pipe and redirect anything that comes to it
# to stderr connected to Docker.
mkfifo -m 600 /tmp/logpipe
cat < /tmp/logpipe 1>&2 &
chown www-data /tmp/logpipe
# Other startup script... without chmod
su -l ${SPUSER:-smokeping} -s /bin/bash -c \
    "exec /usr/sbin/smokeping --logfile=/tmp/logpipe ${DEBUG:+--debug}"
exec lighttpd -D -f /etc/lighttpd/lighttpd.conf 2>&1
```

**Comment by dperson** [comment]
Thank you for the bug report. I wasn't getting the error that you were, but logging still wasn't working correctly either. I hadn't had a chance to get back to it until now. Hopefully, the latest update will fix things for us. Please, pull the latest version and try again.

**Comment by ties** [comment]
Thanks for the quick update to the image. The latest revision* works 👍.

```
*: "Id": "sha256:12ddf443f5e1c34240fb220364861f3a7387d35d442d2bd50a61ce9197e60b21",
```
