### ISSUE TITLE
How to make data persistent?

### ISSUE THREAD

**Issue by oliverkurth** [dperson/smokeping#25]
I am trying to have data persistent, so they survive container restarts and host reboots. I tried this:

docker run -it -p 8000:80 -e SPUSER=root -v /data/smokeping/etc/:/etc/smokeping:ro -v /data/smokeping/lib/:/var/lib/smokeping rpi-smokeping

This works the first time, but when I restart I don't see any new data. It looks like the *.rrd file are never updated.

**Comment by oliverkurth** [comment]
Hm, that was observed on a Raspberry Pi. I tried the same in a Ubuntu VM, and there it works. /data is an NFS mount on the Pi, not sure if that is the issue.

**Comment by dperson** [comment]
I have no idea why, but wouldn't thing that `/data` being NFS would matter. The whole of the debian armhf image is considered highly experimental... so you may have just hit one of the bugs.
