### ISSUE TITLE
Round Trip Time reporting off by a factor of 100

### ISSUE THREAD

**Issue by ericboehs** [dperson/smokeping#26]
This version of SmokePing seems to report stats (including graphs) in tens of microseconds (10^-5) instead of milliseconds (10^-3). For example, my typical response time to Google is 23 milliseconds but SmokePing is reporting this as "230.0 us".

<img width="670" alt="screen shot 2017-03-24 at 1 44 23 am" src="https://cloud.githubusercontent.com/assets/28198/24283395/7d448f96-1033-11e7-9f3a-d1061ac83362.png">

I found [this line](https://github.com/oetiker/SmokePing/blob/master/lib/Smokeping/probes/FPing.pm#L83-L84) of code in SmokePIng's source but I don't think this branch of code is being executed as there is "no need for this if we run as a cgi" (also it's a factor of 1000 rather than 100).

Do you have any suggestions to make the response time reported display correctly?

Thanks!

**Comment by dperson** [comment]
I'll have to fire up a fresh container and play with it. My container uses a volume that I've had in place for years now for persistent storage. But I'm still seeing milliseconds and not microseconds in my output.

**Comment by dperson** [comment]
Can't reproduce.
