### ISSUE TITLE
Loss target after restart container

### ISSUE THREAD

**Issue by NearTan** [dperson/smokeping#30]
Hi dperson,

When I add a target and restart container, the target I just added disappear.

```
near@ ~ $ docker run -it -p 8001:80 -e SPUSER=root --name smokeping1 -d dperson/smokeping -w -t "ISP;NextHop1;google.com" -T "Asia/Shanghai"
60884d34c727a029506eeb2fb3904475273cfb434b462c696f91f90ce9174629
near@ ~ $ docker exec smokeping1 cat /etc/smokeping/config.d/Targets
*** Targets ***

probe = FPing

menu = Top
title = Network Latency Grapher
remark = Welcome to the SmokePing website of xxx Company. \
         Here you will learn all about the latency of our network.


+ ISP
menu = ISP
title = ISP Network

++ NextHop1
menu = NextHop1
title = NextHop1
host = google.com

near@ ~ $ docker exec -it smokeping1 smokeping.sh -t "ISP;NextHop2;bob.dyndns.org"
Service already running, please restart container to apply changes
near@ ~ $ docker exec smokeping1 cat /etc/smokeping/config.d/Targets
*** Targets ***

probe = FPing

menu = Top
title = Network Latency Grapher
remark = Welcome to the SmokePing website of xxx Company. \
         Here you will learn all about the latency of our network.


+ ISP
menu = ISP
title = ISP Network

++ NextHop1
menu = NextHop1
title = NextHop1
host = google.com


++ NextHop2
menu = NextHop2
title = NextHop2
host = bob.dyndns.org

near@ ~ $ docker restart smokeping1
smokeping1
near@ ~ $ docker exec smokeping1 cat /etc/smokeping/config.d/Targets
*** Targets ***

probe = FPing

menu = Top
title = Network Latency Grapher
remark = Welcome to the SmokePing website of xxx Company. \
         Here you will learn all about the latency of our network.



+ ISP
menu = ISP
title = ISP Network

++ NextHop1
menu = NextHop1
title = NextHop1
host = google.com
```

**Comment by dperson** [comment]
I'm not sure what is happening on your system. I've repeated the steps many times now and not been able to reproduce the issue you're seeing.

**Comment by NearTan** [comment]
@dperson It happened both my macOS and Synology NAS, docker version is `17.05.0-ce` or `17.06.2-ce`.

**Comment by dperson** [comment]
@NearTan while I'm running `docker-ce-17.09.0.ce` on Fedora Linux, the only directory that I have as an external volume is `/var/lib/smokeping`. I've modified my container start process to mirror the above, docker compose just starts the smokeping container with the default configuration, then a `docker exec` configures the monitoring, and a `docker restart` makes sure that it is applied to the monitoring. It's working as expected for me... I've been through the process 20x times now with the expected result.

**Comment by dperson** [comment]
@NearTan I'd suggest running the following (it should work around whatever is happening on your systems):
```
docker run -it -p 8001:80 -e SPUSER=root --name smokeping1 -d dperson/smokeping -w -t "ISP;NextHop1;google.com" -T "Asia/Shanghai"
60884d34c727a029506eeb2fb3904475273cfb434b462c696f91f90ce9174629
docker cp smokeping1:/etc/smokeping </path/of/your/choice>
```
Then in the future, starting the container with:
`docker run -it -p 8001:80 -e SPUSER=root --name smokeping1 -v </path/of/your/choice>:/etc/smokeping -d dperson/smokeping -w -T "Asia/Shanghai"
60884d34c727a029506eeb2fb3904475273cfb434b462c696f91f90ce9174629`
Replacing the `</path/of/your/choice>` with an actual path on your filesystem.

**Comment by NearTan** [comment]
@dperson thanks for your help, it works for me but I think I should use a read-only volume.
Finally I run
```
docker run -it -p 8001:80 -e SPUSER=root --name smokeping1 -v ~/smokeping:/etc/smokeping:ro -d dperson/smokeping -w -T "Asia/Shanghai"
```
