### ISSUE TITLE
can't use my alert script

### ISSUE THREAD

**Issue by tianshuangkun** [dperson/smokeping#34]
# alert file：
*** Alerts ***
to=|/etc/smokeping/config.d/alert.sh
from = abc@company.com

+someloss
type = loss
pattern = >0%,*12*,>0%,*12*,>0%
comment = loss
+hostdown
type = loss
pattern = ==0%,==0%,==0%, ==U
comment = no reply

+rttdetect
type = rtt
pattern = >4
comment = yanshi

# my alert.sh

alertname=$1
target=$2
losspattern=$3
rtt=$4
hostname=$5
echo "$(date +%F-%T)" >> invoke.log

# docker log:
Tue Mar 13 09:27:48 2018 - Smokeping version 2.006011 successfully launched.
Tue Mar 13 09:27:48 2018 - Entering multiprocess mode.
Tue Mar 13 09:27:48 2018 - No targets defined for probe EchoPingHttp, skipping.
Tue Mar 13 09:27:48 2018 - Child process 25 started for probe FPing.
Tue Mar 13 09:27:48 2018 - No targets defined for probe EchoPingHttps, skipping.
Tue Mar 13 09:27:48 2018 - All probe processes started successfully.
Tue Mar 13 09:27:48 2018 - FPing: probing 11 targets with step 60 s and offset 34 s.
2018-03-13 09:27:48: (log.c.217) server started 
2018-03-13 09:27:48: (server.c.1295) WARNING: unknown config-key: setenv.add-response-header (ignored) 
Tue Mar 13 09:28:37 2018 - Alert rttdetect is active for Other.f5-w1-net-11bee-br
Tue Mar 13 09:29:37 2018 - Alert rttdetect is active for Other.f5-w1-net-11bee-br
Tue Mar 13 09:30:36 2018 - Alert rttdetect is active for Other.f5-w1-net-11bee-br
Tue Mar 13 09:30:36 2018 - Alert rttdetect is active for Other.csr1-net-11bee-br
Tue Mar 13 09:30:36 2018 - Alert someloss is active for Other.csr1-net-hf-11bee-br
Tue Mar 13 09:31:37 2018 - Alert rttdetect is active for Other.f5-w1-net-11bee-br
Tue Mar 13 09:31:37 2018 - Alert someloss is active for Other.csr1-net-hf-11bee-br
Tue Mar 13 09:32:37 2018 - Alert rttdetect is active for Other.f5-w1-net-11bee-br

# alert is triggered,but my file invoke.log is alway empty

why alert not use my alert script?   anyone meet this question?

**Comment by dperson** [comment]
I've never used that option, but looking at the `alert.sh` script, you're not setting the directory where it will write to `invoke.log`. It may well be writing to a file named `invoke.log`, just in `/tmp`, `var`, `/run`, or similar.
