### ISSUE TITLE
Empty graphs

### ISSUE THREAD

**Issue by cimm** [dperson/smokeping#5]
I pulled the latest version but the graphs don't seem to work. Added a few targets and they show up but I only get empty graphs, even for the default local machine one. I checked the `docker logs smokeping` logs but that doesn't show anything out of the ordinary.

The SmokePing wiki indicates it could be related to access rights: https://github.com/oetiker/SmokePing/wiki/FAQ

Tried running SmokePing in debug mode in the container but no luck so far.

Thank you.

**Comment by dperson** [comment]
In the startup script I fix the permissions (see below). My container is still working. I'll start a new instance, and see if I can spot the problem.

chown -Rh smokeping:www-data /var/cache/smokeping /var/lib/smokeping \           
            /var/run/smokeping                                                   
chmod -R g+ws /var/cache/smokeping /var/lib/smokeping /var/run/smokeping

**Comment by dperson** [comment]
It's generating charts for me... there is definitely lag from when the service is started to when there's enough data to graph. Just let it run 30-60 minutes and check back. The lag isn't due to Docker AFAIK, smokeping just always has that delay.

**Comment by cimm** [comment]
Feel free to keep this issue closed but wanted to add some background if anyone would have the same problem.

Here is what happens for me (using boot2docker on OS X):

1. Pull the latest `dperson/smokeping`
2. Run `docker run -p 8000:80 -d dperson/smokeping`
3. Wait an hour and check the Local Machine graph, nothing there

I also noticed I can not stop smokeping using the service. Running `service smokeping stop` fails and gets the process in a defunct state:

It **does work** when I replace the `service smokeping start` with `/usr/sbin/smokeping` in the [smokeping script](https://github.com/dperson/smokeping/blob/master/smokeping.sh#L183). Alternatively changing the `DAEMON_USER` to `root` in the smokeping init script works as well.

**Comment by braddeicide** [comment]
I had the same issue, the /usr/sbin/smokeping suggestion fixed it.  I'm using it in CoreOS, Docker 1.5.0

**Comment by jensmh** [comment]
I've also experienced the same issue, and was able to resolve using @cimm 's suggestion of replacing `service smokeping start` with `/usr/sbin/smokeping` on [line 185 of smokeping.sh](https://github.com/dperson/smokeping/blob/master/smokeping.sh#L185) . I'm running smokeping on a Synology NAS running DSM 5.2, Docker 1.5.0.

**Comment by oppianmatt** [comment]
I'm having the same issue. Left it running all night and no results. Running ubuntu 14.04 Docker version 1.6.2, build 7c8fca2

should this be reopned and fixed?

**Comment by dperson** [comment]
Okay, I've updated the startup script. If it fails to start smokeping as
non-root, it will try again as root. That should work around the issue that
you're seeing.

The build should finish up in just a few minutes and be ready to pull.

-- 
David P.

**Comment by oppianmatt** [comment]
Been trying this out, don't think it works. Still no data in the graphs. It seems in the docker instance smokeping needs to be run as root and not the smokeping user.

```
matt@rock ~ ➤ docker exec -it smokeping bash
root@93cc287b49c7:/# ps -auxx
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
www-data     1  0.0  0.1  72464  7580 ?        Ss   11:11   0:00 lighttpd -D -f /etc/lighttpd/lighttpd.conf
root        14  0.0  0.7 168324 28972 ?        Ss   11:11   0:00 /usr/sbin/smokeping [FPing]
root        84  1.0  0.0  20216  3068 ?        Ss   13:31   0:00 bash
root        88  0.0  0.0  17492  2084 ?        R+   13:31   0:00 ps -aux
root@93cc287b49c7:/# exit

matt@rock ~ ➤ docker exec -it smokeping2 bash
root@c07cb421b7c7:/# ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
www-data     1  0.0  0.1  72836  5960 ?        Ss   13:26   0:00 lighttpd -D -f /etc/lighttpd/lighttpd.conf
smokepi+    21  0.0  0.7 168300 29664 ?        Ss   13:26   0:00 /usr/sbin/smokeping [FPing]
root        42  1.0  0.0  20216  3072 ?        Ss   13:31   0:00 bash
root        46  0.0  0.0  17492  2084 ?        R+   13:31   0:00 ps -aux
```

The first one works when it runs as root which is when /usr/sbin/smokeping is invoked instead of service. Whilst the second one is the service one. I don't think the issue was that smokeping failed to start, I think the issue was that it needs root somewhere as another fix mentioned above is to set the DAEMON_USER to root. 

But question is, does it even need service? If it's a docker might as well just start it with /usr/sbin/smokeping and call it a day.

**Comment by dperson** [comment]
Ah, I misunderstood. I thought that smokeping was exiting on the systems
that were having the problem, unless run as root.

Hmm, how about I make it read an environment variable, to have it run as
root?

-- 
David P.

**Comment by jhautefeuille** [comment]
I've same problem, I've just download last image.
Smokeping run but graphes are not done.
I'm running Docker on synology.

If I want to trace I must run as

docker exec smokeping --debug in crontab of synology...

**Comment by dperson** [comment]
*facepalm* - I added the option to specify the user for smokeping, but
didn't document it. Sorry guys. It's in the README.md now.

But you can now set the environment variable SPUSER to root (add the
following argumnets to your docker run or add to you docker compose yml
file `-e SPUSER=root`). That will run smokeping as root for those of you
where it's not running correctly as non-root. I'm still not sure why it's
having a problem for you... but it should work around it.

Thanks.

-- 
David P.
