### ISSUE TITLE
FastCGI Working?

### ISSUE THREAD

**Issue by philcolbourn** [dperson/smokeping#6]
Although FastCGI module is enabled, it appears no faster then my CGI version on same machine.

1. How do I confirm fastCGI is running
2. Do I need to use a different URL?

**Comment by dperson** [comment]
From Wikipedia: FastCGI's main aim is to reduce the overhead associated with interfacing the web server and CGI programs, allowing a server to handle more web page requests at once.  

So it's not really going to change a one user environment that much, it's more for the ability to scale to *many* users. It was simple and easy to enable, and there's no downside. You don't need a separate URL, just use it normally. Hope this helps.

**Comment by philcolbourn** [comment]
Ok. I don't know enough to argue on whether it should be fast or not.

BTW, I like your docker image (is that what they are called?)

In the dockerfile the script modifies 15-fastcgi-php.conf but enables
fastcgi.

Should fastcgi-php be enabled as well?



Phil

**Comment by dperson** [comment]
Actually the modification of 15-fastcgi-php.conf isn't needed in this container (it doesn't use PHP). It came from another container (OwnCloud) that also needed a lightweight web server to function.

**Comment by philcolbourn** [comment]
Ok. That makes sense now.

I have now managed to get FastCGI working and it is much faster.

My configuration is not optimal as I have been hacking until I got fastcgi
to work.

Before 23:40 I was monitoring smokeping.cgi. Then I successfully got
fastcgi working.

Responses are about 1s faster and about 5 times faster.



Would you like my config to consider for your docker image?



Phil

**Comment by philcolbourn** [comment]
Sorry, forgot to attach graph


Phil

**Comment by dperson** [comment]
Yes please do submit the configuration change. I'll be glad to include it. Thank you.

**Comment by philcolbourn** [comment]
Ok, again, I am not confident with what I am doing.
Also, I'm running Ubuntu 15.04.

Directorys

/usr/lib/cgi-bin/

  smokeping.cgi

/var/www/
  smokeping -> /usr/share/smokeping/www

/var/www/smokeping/
  smokeping.fcgi

I had a minor edit in this file, changing smokeping_cgi to smokeping.cgi -
a '_' to a '.'


Attached:

  /etc/lighttpd/lighttpd.conf
  /etc/lighttpd/conf-available/10-cgi.conf
  /etc/lighttpd/conf-available/10-fastcgi.conf  (with debug enabled)

This change tells lighttpd to run smokeping.fcgi for all .fcgi files.

This is clearly wrong and needs to be fixed.

Since smokeping uses bash and exec to run smokeping.

I assumed smokeping.fcgi was bin-path to run.

tail -F /var/log/lighttpd/error.log seems to confirm this.


  (my 15-fastcgi-php.conf is commented out and not loaded)

  smokeping.fcgi



Phil

**Comment by dperson** [comment]
Thanks again, I didn't realize it was broken upstream. I've added your fix.

**Comment by philcolbourn** [comment]
that was fast! thanks!

Should it be in docker repo yet?


Phil

**Comment by dperson** [comment]
Yes, if you pull an update it should be there. Thanks for noticing the issue.

**Comment by philcolbourn** [comment]
Great.

I just got caught by docker's proxy 'feature'.

I don't know how to update a docker container (yet) so I removed it and
made a new container running on port 8000 with my host's /etc/smokeping/
directory mapped to docker container..

I can access

http://localhost:8000/cgi-bin/smokeping.cgi

and

http://localhost:8000/smokeping/smokeping.cgi

but not

http://localhost:8000/smokeping/smokeping.fcgi




Phil

**Comment by dperson** [comment]
Actually smokeping.fcgi was a wrapper to spawn the perl fastcgi processes. I finally tracked down how to get perl fastcgi working with lighttpd. Sorry for the long delay, but it's working (at last)!
