### ISSUE TITLE
Adding new host to the running instance

### ISSUE THREAD

**Issue by tombatossals** [dperson/smokeping#7]
Hi, I'm trying to add a new target but I receive an error and the host it's not added to the monitoring.

Example:

```
$ docker exec berserk_einstein smokeping.sh -t "Frankfurt;Nexthop;130.206.211.77"
Starting latency logger daemon: smokeping already running.
2015-05-14 16:51:55: (network.c.409) can't bind to port:  80 Address already in use 
```

Any hint? Thanks

**Comment by dperson** [comment]
The configuration was updated, but the script tries to start the smokeping daemon at the end... probably not desired behavior. Thanks for pointing that out. I'll update the configuration/start scripts today.

**Comment by dperson** [comment]
Okay it's been updated, you shouldn't get that error in the future. Thanks for reporting it.

**Comment by tombatossals** [comment]
Thanks so much!
