### ISSUE TITLE
smokeping container doesn't start

### ISSUE THREAD

**Issue by sir-buckyball** [dperson/smokeping#8]
I'm having trouble starting the smokeping container. I'm a docker noob so it's possible I've just made a rookie mistake.

```
ubuntu@arm:~$ date
Mon May 25 19:26:11 UTC 2015
ubuntu@arm:~$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
dperson/smokeping   latest              da622a416bfd        4 days ago          205.6 MB
ubuntu@arm:~$ sudo docker run --name smokeping -p 8000:80 -d dperson/smokeping
9c146f9a6d17079f510fafbe4a404da2d75a58fcb0e75df04ac36ef0a29ae2a9
ubuntu@arm:~$ sudo docker ps -a
CONTAINER ID        IMAGE                      COMMAND             CREATED             STATUS                     PORTS               NAMES
9c146f9a6d17        dperson/smokeping:latest   smokeping.sh        11 seconds ago      Exited (1) 6 seconds ago                       smokeping       
ubuntu@arm:~$ sudo docker logs smokeping
2015/05/25 19:26:35 exec format error
```

**Comment by dperson** [comment]
Your host name `'arm'` and the `'exec format error'`, lead me to believe that your server is running an ARM (non-x86_64) platform. AFAIK (As Far As I Know), all the images on the docker hub are x86_64 only.  

While you can't use the pre-built images on the hub, you've already made it to the repo where all the files needed to build the container are located. If you run the following, you can build it yourself:

 git clone https://github.com/dperson/smokeping.git
 cd smokeping
 docker build smokeping

I'm afraid you'll have the same issue for everything on docker hub.

**Comment by sir-buckyball** [comment]
Thanks for the info. I am trying to run this on a beaglebone black which is ARM based and didn't realized docker was limited to x86.

**Comment by sir-buckyball** [comment]
For the record, the following change to Dockerfile made things work on a BeagleBone Black. Thanks again for the pointer.

```
-FROM debian:jessie
+FROM armbuild/debian:jessie
```
